#!/bin/bash
set -e
cd "$(dirname "$0")/.."

source scripts/_env

export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER="${CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER:-wasm-server-runner}"

RUSTFLAGS="$WASM32_RUSTFLAGS" cargo +nightly run --target wasm32-unknown-unknown --example panic "$@"
