#!/bin/bash
set -e
cd "$(dirname "$0")/.."

source scripts/_env

CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER="wasm-bindgen-test-runner" RUSTFLAGS="$WASM32_RUSTFLAGS" cargo +nightly test --target=wasm32-unknown-unknown --test thread_log "$@"
